### ISSUE TITLE
Unlicensed AIDA Business 64

### ISSUE THREAD

**Issue by mhowellcit** [mathoudebine/turing-smart-screen-python#10]
In order to get the screen to turn on, I have to use your USBMonitor.exe app, which then ties it to a buggy portable unlicensed version of AIDA64 Business, which may be software piracy.  

I want the option to use this screen with a licensed version of AIDA64extreme.  Additionally, the unlicensed version of AIDA64 business you are trying to force me to use with this monitor system is very buggy and opens full screen on my desktop.  It will not minimize and refreshes AIDA64business (unlicensed version) in the foreground in full screen about once every 3 seconds.  This prevents any program whatsoever from being able to be used in the foreground when the USBmonitor.exe program is active.

I want to use this device with my own licensed copy of AIDA64extreme, which appears to have support for this screen type built in already.  I don't want to be forced to use your unlicensed version of the program.  I also don't want your USBMonitor.exe monitor to keep AIDA64 alive every 3 seconds or at all.  That function completely interrupts every program I run, every time it polls the computer.  This makes the computer impossible to use once USBMonitor.exe is active.

I simply want a switch that turns the screen on and lets me use it with my licensed copy of AIDA64extreme.  Otherwise, this hardware device is worse than completely and totally useless to me, its actively disruptive to my computer system and I will be returning it.

**Comment by mathoudebine** [comment]
Hi, this is not the repository for the official Windows app for the Turing smart screen.
This open-source project is an alternative Python script to do some simple operations on the screen without using USBMonitor.exe.
For support on the official app, please contact the seller of your screen
