### ISSUE TITLE
Put "DISPLAY_ORIENTATION" and "DISPLAY_RGB_LED" in the config.yaml

### ISSUE THREAD

**Issue by Rollbacke** [mathoudebine/turing-smart-screen-python#102]
In a general way, put all the configuration in the "config.yaml".

When you clone the project, I think the only file you should modify should be the "config.yaml" (for me, I have to set the orientation as reverse).

**Comment by mathoudebine** [comment]
Hello @Rollbacke

I'm not sure the DISPLAY_ORIENTATION should be fully moved to config.yaml: the basic orientation (portrait or landscape) is theme-dependent. Maybe the theme can keep only the portrait/landscape specificity whereas the config.yaml can hold a "reverse" boolean property to reverse the theme orientation.

As for the DISPLAY_RGB_LED, the idea was also to allow theme creators to define an RGB color that matches the theme (e.g. yellow for the Cyberpunk theme, etc.)
To allow user modification, maybe the config.yaml can hold an optional property to override this settings. If the property is not defined/empty, then the theme would apply the pre-defined RGB color.

What do you think?

**Comment by Rollbacke** [comment]
Hi @mathoudebine,
You're right, I hadn't thought of landscape themes. Indeed, in this case, it's necessary to keep the orientation in the yaml file of the theme.
A boolean reverse is a good idea !
OK for the DISPLAY_RGB_LED, I agree with you ;)

**Comment by mathoudebine** [comment]
Thanks for the feedback, i've added a `DISPLAY_REVERSE` boolean in `config.yaml` in the last release and i will think of how to implement the RGB LED override!

**Comment by Rollbacke** [comment]
I was just reading the changelog for the latest version.
It's really great. Great job for the LibreHardwareMonitor implementation, it's amazing !
