### ISSUE TITLE
 signal handler does not seem to work for Windows platform.

### ISSUE THREAD

**Issue by 1080papaya** [mathoudebine/turing-smart-screen-python#105]
**Describe the bug**  
Cannot enter keyboard interrupt through command line once GPUtil library has loaded.

**To Reproduce**  
1. load .py script (e.g. main)
2. wait till gpu libraries are loaded
3. cannot enter any input

**Expected behavior**  
keyboard interrupt to properly self.lcd.Reset() class or similar to clear screen.

**Screenshots / photos of the Turing screen**  
N/A

**Environment:**  
 - Revision of this project [MAIN]
 - OS with version [Windows 11]
 - Python version [e.g. Python 3.8]
 - Hardware [Intel CPU, Nvidia GPU]

**Additional context**  
Hi @mathoudebine,
we've already discussed this a bit in the Q/A, im reposting here.

use case:  im starting main.py through command line (py main.py)

I ended up creating a file called kill.py and a batch file to first kill python in my processes and then load kill.py - which is basically identical to display.py except i've removed as much code as i can so that it only executes self.lcd.Reset().

The screen does need to be physically unplugged sometimes though as i've encounted random artifcating after several screen refresh/resets. Although to be fair I may have a differnt use case scenerio than most other people.

I'm using Playnite (game launcher) to automatically load a .bat file based on the game i launch, the batch file will load up the correseponding game theme file that i have created (modified theme with a background based on the game im playing).
upon quitting the game playnite will auto-execute a seperate batch file to unload the screen.

so far this way is working fine for me, although when i get to self.lcd.reset() the screen will still display text to load the default turing application - i dont think there's anything that can be done here except physically disconnecting the screen if i want to completely shutdown the screen.

**Comment by mathoudebine** [comment]
Issue has been fixed with #132
Fix is included from release 2.3.1
