### ISSUE TITLE
New Board Revision?

### ISSUE THREAD

**Issue by airfield20** [mathoudebine/turing-smart-screen-python#107]
**Describe the bug**  
My board is not shown in the images of the board revision, however Rev A configuration works on linux (when reset is disabled)

**To Reproduce**  
N/A

**Expected behavior**  
N/A

**Screenshots / photos of the Turing screen**  
Add screenshots or photos of the rendering on the Turing screen to help explain your problem.
![PXL_20221216_030212692](https://user-images.githubusercontent.com/9437975/208015351-3df84917-c075-4315-9e92-c0e3edb35979.jpg)
 

**Environment:**  
 - Ubuntu 20

**Additional context**  
board was purchased from amazon, shipped from china.

**Comment by mathoudebine** [comment]
I've never seen this board! Must be a new revision A. Can you send the link where you bought it please?
I will update the documentation with your photo if that's okay

**Comment by airfield20** [comment]
hokistudio 3.5 Inch 480x320 IPS TYPEC Screen for Aida64 PC CPU Monitor Computer Temperature with Metal Shell https://a.co/d/4wBgbpV

Sure that's fine with me

**Comment by mathoudebine** [comment]
Documentation updated
