### ISSUE TITLE
Use win32api.setConsoleCtrlHandler() to receive shutdown/logoff events from Windows

### ISSUE THREAD

**Issue by mathoudebine** [mathoudebine/turing-smart-screen-python#132]
**Is your feature request related to a problem? If so, please describe the problem.**  
If system monitor is launched using Task Manager, when shutting down the computer the screen does not turn off, it stays on with the latest displayed data.

**Describe the feature / solution to your problem you'd like**  
Use `win32api.setConsoleCtrlHandler()` to receive shutdown/logoff events from Windows and stop cleanly (screen will turn off)

**Describe alternatives you've considered / and or tested**  
Stopping using the tray icon each time before shutting down the computer but it's not automatic

**Environment:**  
 - OS: Windows (all versions)

**Comment by Rollbacke** [comment]
Hi,
I want to clarify that there is no problem with systemd on Linux. It stops cleanly.
The problem is really only with Windows.

**Comment by mathoudebine** [comment]
This PR can also implement the `atexit` callback register like here: https://stackoverflow.com/questions/3850261/doing-something-before-program-exit/72592788#72592788

**Comment by Rollbacke** [comment]
Hi @mathoudebine,
How are you doing while waiting this on Windows? I forget to turn off the screen at least 2 out of 3 times -_-
I thought about making a little python script that would be called on extinction (not sure if that's possible).

**Comment by mathoudebine** [comment]
Hello @Rollbacke
This should now be implemented in the latest release!

**Comment by Rollbacke** [comment]
It works great!  Thanks @mathoudebine ! 😎
