### ISSUE TITLE
Start by Windows task scheduler does not turn off the screen on shutdown

### ISSUE THREAD

**Issue by Rollbacke** [mathoudebine/turing-smart-screen-python#133]
Hi @mathoudebine, 

As the title says, a start by Windows (11) task scheduler does not turn off the screen on shutdown.
I think it's simply because it kills the process uncleanly.
I'm not sure there is a solution currently, except to call another python script that resets the screen.

**Comment by mathoudebine** [comment]
There might be a solution in #132 that i will try to implement (catching a logout signal) but it will work only if the program is not killed before

**Comment by Rollbacke** [comment]
Oh, OK !
I didn't see it ! I close this one ;)
