### ISSUE TITLE
Tray icon isn't displayed when called from pythonw

### ISSUE THREAD

**Issue by Cyruz143** [mathoudebine/turing-smart-screen-python#155]
**Describe the bug**  
Tray icon isn't displayed when called from pythonw. Potentially a limitation of pythonw, works fine if you call from command line with python.

**To Reproduce**  
1. Load via pythonw, no tray icon

**Expected behavior**  

**Screenshots / photos of the Turing screen**  
Add screenshots or photos of the rendering on the Turing screen to help explain your problem.
You can drag and drop photos here to add them to the description.

**Environment:**  
 - 2.3.0
 - Windows 10 x64
 - Python 3.10.6
 - AMD CPU + Nvidia GPU

**Additional context**  
N/A

**Comment by mathoudebine** [comment]
How do you start pythonw?
When I use this command line `pythonw.exe main.py` the tray icon is displayed on my computer with the same setup as yours.
Are you sure the icon is not in the hidden icons panel?

**Comment by Cyruz143** [comment]
Crap, should have checked that. It's fine direct from PS but if you use the task scheduler to start it, it doesn't fire the tray icon.

**Comment by Cyruz143** [comment]
Ok, closing this. Removed the task and recreated and now it works fine. Can't quite explain why!
