### ISSUE TITLE
DeprecationWarning: textsize is deprecated and will be removed in Pillow 10

### ISSUE THREAD

**Issue by Pierrot66657** [mathoudebine/turing-smart-screen-python#18]
hello,
/home/pi/turing/main.py:153: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = d.textsize(text, font=font)

I tried to replace but without success.

thank you

**Comment by mathoudebine** [comment]
Hi @Pierrot66657 
The issue is now fixed in latest commit on main branch, and also in latest release 1.1.1
Thanks!
