### ISSUE TITLE
Sensor inite failed

### ISSUE THREAD

**Issue by Babimn** [mathoudebine/turing-smart-screen-python#206]
I was previously using this monitor, and I've changed my motherboard from MSI 560 to MSI z690. and now it can now start.
error is Sensor Inite failed. How to resolve this guys

**Comment by mathoudebine** [comment]
Hello, can you provide a screenshot of the error?
Do you start the program manually or using the Task Scheduler?

**Comment by mathoudebine** [comment]
Closed for inactivity, add a comment and tag me if you want to re-open it
