### ISSUE TITLE
struct.pack used incorrectly for image data

### ISSUE THREAD

**Issue by braewoods** [mathoudebine/turing-smart-screen-python#207]
I was reviewing the source code and noticed that the usage of `struct.pack` is incorrect and just happens to work by chance. The Turing Smart Screen expects image data to be in little endian byte order and the code as written will only work correctly if the host CPU is also little endian. This is rarely going to be a problem but if someone tries to run the current code on a big endian host it will transmit image data that has the pixel bytes in the wrong byte order. The remedy is simple, just change the packing string to `<H` and it will be guaranteed to be in the correct byte order. This follows existing python API documentation, found here:
https://docs.python.org/3/library/struct.html

**Comment by mathoudebine** [comment]
Thanks, there is already this PR #196 for Rev.B display but it should also be done for Rev. A display as well
