### ISSUE TITLE
Is this the correct 5" Screen?

### ISSUE THREAD

**Issue by Paradoxum** [mathoudebine/turing-smart-screen-python#226]
**Describe the bug**  
After [DEBUG] Found one supported GPU: AMD Radeon RX 6900 XT, no more output in console and display does not change.

**To Reproduce**  

**Expected behavior**  
Display to work.

**Screenshots / photos of the Turing screen**  
https://streamable.com/a91cqz

**Environment:**  
 - latest source 
 - w11 2H22 22624.1690
 - latest from the site (3.11?)
 - radeon 6900 xt gpu, screen: https://www.aliexpress.com/item/1005004845450763.html

**Additional context**  
Not sure if this is the right 5" screen: https://www.aliexpress.com/item/1005004845450763.html
But I've got it working fine on my 3.5 model.
https://streamable.com/fp1uv8

  COM_PORT: COM3 as discovered in device manager when I pull/plug in the screen. Tried auto too.

**Comment by mathoudebine** [comment]
Hi, the 5" version is not supported by this project because it uses a different command set than the 3.5"
Support will be added later, it is currently in development: see #90 for updates

**Comment by Paradoxum** [comment]
Ah ok thank you. Got it working fine with my 3.5" one:
https://streamable.com/ugmuak

Finding the turx.com software to be awful. Arranging a theme it's back like when I made my own UI for my Nexus years ago. Moving single wigets around the screen with coordinates and everything (I know you can drag but there isn't even a border snap).

Even thinking of setting up a small site where people can easily upload and download themes for these things, cause the 'store' on the official app sucks, you can't even upload anything to it outside of taiwan or wherever it was made even using a vpn. But yeah it'd just be a basic login upload theme / fill out details post people can download maybe comment / rate I dunno.
