### ISSUE TITLE
Only a relatively minor edit, but I like the higher contrast and the red bars match my PC lighting. It's not pixel perfect but the display softens the edges and it looks fine in person.

### ISSUE THREAD

**Issue by Citywolf01** [mathoudebine/turing-smart-screen-python#243]
Only a relatively minor edit, but I like the higher contrast and the red bars match my PC lighting. It's not pixel perfect but the display softens the edges and it looks fine in person.
![image](https://user-images.githubusercontent.com/125101447/218227131-55277ea9-8710-42f0-afb4-2e2acf377ab6.png)
![background](https://user-images.githubusercontent.com/125101447/218227137-79aec3ac-14a1-486d-afe2-c432bb519b20.png)
Background is 50, 50, 50 (323232)
Bars are 255, 0, 0

_Originally posted by @Pepper-the-kobold in https://github.com/mathoudebine/turing-smart-screen-python/discussions/58#discussioncomment-4940788_

**Comment by mathoudebine** [comment]
Hello, i think you clicked on "Reference in new issue" by mistake so i'm closing this issue, because there is nothing more than the original comment.
You can use the [Discussion space](https://github.com/mathoudebine/turing-smart-screen-python/discussions) to discuss about themes and ask questions
