### ISSUE TITLE
Alternative implementation as object-oriented interface (with MIT license)

### ISSUE THREAD

**Issue by gerph** [mathoudebine/turing-smart-screen-python#29]
**Is your feature request related to a problem? If so, please describe the problem.**  

The problem I had was that this repo is licensed under a restrictive license that precludes my using it in my project. Additionally, I wanted to provide support for the two variants using object oriented interfaces - with the version B and version A sharing common interfaces and code.

I also wanted to be able to add the ability to invert the content easily - something I now see is also possible in the hardware A implementation.

So I wrote a new library for myself, using the information - but none of the code - from this project.

This can be found here:

https://github.com/gerph/turing-smart-screen-python-mit

**Describe the feature / solution to your problem you'd like**  

As I needed this library for myself in my project, I had to re-write it from scratch, but it might as well be available to anyone. Some of what I've done in my version is almost certainly reusable within this project - and because it's MIT licensed, that's quite compatible with integration into GPL projects such as this.

What does the my repo offer that this code doesn't?

Not that much really.

* Primarily it was written so that I didn't have to use GPL code, and to be Python 2/3 compatible.
* The class based implementation means that the two variants can have the same interface and be descended from the same base class.
* This means that hardware features not provided can be implemented in software, or report errors.
* The implementation also provides for inverting the rendering of the bitmap (in software), ie flipping the image horizontally or vertically.
* The sleep-between-bitmap-data has been reworked so that the sleeping happens only when necessary when the next command happens, rather than being forced at the end of a bitmap update. This should be more efficient as it allows the python to get on with other things rather than stalling, and only sleeps when it's absolutely necessary.
* And there's a constructor function that uses the fact that the old interfaces don't respond to HELLO to select the correct objects.

Take the code and use it if you want. Take the ideas. It's freely given under MIT license.

I've tested my code with the example functions in this repository and it appears to work quite well with my library switched in.

**Describe alternatives you've considered / and or tested**  

I briefly considered requesting the change to the license from GPL, but people that select GPL are commonly averse to changing away from it, and with multiple contributors who might need to agree to such a change, it wasn't worth it. Easier to just re-write it.

**Screenshots / photos & mockups of the Turing screen**  

Not really screenshots, but the example code that I've been using from this project (which is not part of the MIT version) can be used with the new library. Readlly the only bits that were changed were the functions in the test code which performed operations - they were just updated to call the object instead of doing the work themselves.

```python
#!/usr/bin/env python3
# A simple Python manager for "Turing Smart Screen" 3.5" IPS USB-C display
# https://github.com/mathoudebine/turing-smart-screen-python

import os
import signal
import struct
from datetime import datetime
from time import sleep

import serial  # Install pyserial : pip install pyserial
from PIL import Image, ImageDraw, ImageFont  # Install PIL or Pillow

# Set your COM port e.g. COM3 for Windows, /dev/ttyACM0 for Linux...
COM_PORT = "/dev/ttyACM0"
# COM_PORT = "COM5"
# MacOS COM port:
COM_PORT = '/dev/cu.usbmodem2017_2_251'

# The new device has a serial number of '2017-2-25'


import turing_smart_screen


def Clear(display):
    # Unknown what command this is
    print("Clear display")
    display.clear()


def Orientation(display, state: int):
    print("Orientation: %r" % (state,))
    display.orientation(state)


def SetLighting(display, red: int, green: int, blue: int):
    print("Lighting: %i, %i, %i" % (red, green, blue))
    display.backlight(red, green, blue)


def ScreenOff(display):
    print("Screen off")
    display.enable(False)


def ScreenOn(display):
    print("Screen on")
    display.enable(True)


def SetBrightness(display, level: int):
    # Level : 0 (brightest) - 255 (darkest)
    assert 255 >= level >= 0, 'Brightness level must be [0-255]'
    # New protocol has 255 as the brightest, and 0 as off.
    display.brightness(255 - level)


def DisplayPILImage(display, image: Image, x: int, y: int):
    display.update_region_pillow(x, y, image)


def DisplayBitmap(display, bitmap_path: str, x=0, y=0):
    image = Image.open(bitmap_path)
    DisplayPILImage(display, image, x, y)


def DisplayText(display, text: str, x=0, y=0,
                font="roboto/Roboto-Regular.ttf",
                font_size=20,
                font_color=(0, 0, 0),
                background_color=(255, 255, 255),
                background_image: str = None):
    # Convert text to bitmap using PIL and display it
    # Provide the background image path to display text with transparent background

    assert len(text) > 0, 'Text must not be empty'
    assert font_size > 0, "Font size must be > 0"

    if background_image is None:
        # A text bitmap is created with max width/height by default : text with solid background
        text_image = Image.new('RGB', (display.WIDTH, display.HEIGHT), background_color)
    else:
        # The text bitmap is created from provided background image : text with transparent background
        text_image = Image.open(background_image)

    # Draw text with specified color & font (also crop if text overflows display)
    font = ImageFont.truetype("./res/fonts/" + font, font_size)
    d = ImageDraw.Draw(text_image)
    d.text((x, y), text, font=font, fill=font_color)

    # Crop text bitmap to keep only the text
    left, top, text_width, text_height = d.textbbox((0,0), text, font=font)
    text_image = text_image.crop(box=(x, y, min(x + text_width, display.WIDTH), min(y + text_height, display.HEIGHT)))

    DisplayPILImage(display, text_image, x, y)


def DisplayProgressBar(display, x: int, y: int, width: int, height: int, min_value=0, max_value=100,
                       value=50,
                       bar_color=(0, 0, 0),
                       bar_outline=True,
                       background_color=(255, 255, 255),
                       background_image: str = None):
    # Generate a progress bar and display it
    # Provide the background image path to display progress bar with transparent background

    assert x + width <= display.WIDTH, 'Progress bar width exceeds display width'
    assert y + height <= display.HEIGHT, 'Progress bar height exceeds display height'
    assert min_value <= value <= max_value, 'Progress bar value shall be between min and max'

    if background_image is None:
        # A bitmap is created with solid background
        bar_image = Image.new('RGB', (width, height), background_color)
    else:
        # A bitmap is created from provided background image
        bar_image = Image.open(background_image)

        # Crop bitmap to keep only the progress bar background
        bar_image = bar_image.crop(box=(x, y, x + width, y + height))

    # Draw progress bar
    bar_filled_width = value / (max_value - min_value) * width
    draw = ImageDraw.Draw(bar_image)
    draw.rectangle([0, 0, bar_filled_width-1, height-1], fill=bar_color, outline=bar_color)

    if bar_outline:
        # Draw outline
        draw.rectangle([0, 0, width-1, height-1], fill=None, outline=bar_color)

    DisplayPILImage(display, bar_image, x, y)


stop = False

if __name__ == "__main__":

    def sighandler(signum, frame):
        global stop
        stop = True


    # Set the signal handlers, to send a complete frame to the LCD before exit
    signal.signal(signal.SIGINT, sighandler)
    signal.signal(signal.SIGTERM, sighandler)
    is_posix = os.name == 'posix'
    if is_posix:
        signal.signal(signal.SIGQUIT, sighandler)

    # Do not change COM port settings unless you know what you are doing
    ser = serial.Serial(COM_PORT, 115200, timeout=1, rtscts=1)

    lcd_comm = turing_smart_screen.TuringDisplayAutoSelect(ser)

    # Hello! to check this is the right device
    Hello(lcd_comm)

    # Data orientation
    Orientation(lcd_comm, lcd_comm.ORIENTATION_PORTRAIT)

    # Clear the display
    Clear(lcd_comm)
    ScreenOn(lcd_comm)

    # Set brightness to max value
    SetBrightness(lcd_comm, 0)

    # Lighting (a purple)
    SetLighting(lcd_comm, 128, 50, 112)

    lcd_comm.invert(lcd_comm.INVERT_XY)

    # Display sample picture
    print("Update display")
    DisplayBitmap(lcd_comm, "res/example.png")

    # Display sample text
    DisplayText(lcd_comm, "Basic text", 50, 100)

    # Display custom text with solid background
    DisplayText(lcd_comm, "Custom italic text", 5, 150,
                font="roboto/Roboto-Italic.ttf",
                font_size=30,
                font_color=(0, 0, 255),
                background_color=(255, 255, 0))

    # Display custom text with transparent background
    DisplayText(lcd_comm, "Transparent bold text", 5, 300,
                font="geforce/GeForce-Bold.ttf",
                font_size=30,
                font_color=(255, 255, 255),
                background_image="res/example.png")

    # Display text that overflows
    DisplayText(lcd_comm, "Text overflow!", 5, 430,
                font="roboto/Roboto-Bold.ttf",
                font_size=60,
                font_color=(255, 255, 255),
                background_image="res/example.png")

    # Display the current time and some progress bars as fast as possible
    bar_value = 0
    while not stop:
        DisplayText(lcd_comm, str(datetime.now().time()), 160, 2,
                    font="roboto/Roboto-Bold.ttf",
                    font_size=20,
                    font_color=(255, 0, 0),
                    background_image="res/example.png")

        DisplayProgressBar(lcd_comm, 10, 40,
                           width=140, height=30,
                           min_value=0, max_value=100, value=bar_value,
                           bar_color=(255, 255, 0), bar_outline=True,
                           background_image="res/example.png")

        DisplayProgressBar(lcd_comm, 160, 40,
                           width=140, height=30,
                           min_value=0, max_value=19, value=bar_value % 20,
                           bar_color=(0, 255, 0), bar_outline=False,
                           background_image="res/example.png")

        bar_value = (bar_value + 2) % 101

    SetLighting(lcd_comm, 0, 0, 0)

    ScreenOff(lcd_comm)

    ser.close()
```

**Additional context**  

Thanks for the library, and I might try to integrate the object interface into the system monitor branch later, as it looks like that's going the object oriented route which might benefit from that interface.

**Comment by mathoudebine** [comment]
Hi and sorry for the license inconvenience.

The original reason of choosing GPLv3 was to avoid people making and distributing closed source versions of this repository. I do not want the product manufacturer and/or seller to package and distribute this as if it was their original software.
Sorry to learn that you needed to re-implement everything from scratch.

As you have seen, this project will soon switch to an object-oriented implementation with the 2.0 release, so i will not maintain the current release anymore. Thanks for the example code though.
I pinned this issue in case other people have issues with the GPL license.

**Comment by gerph** [comment]
That's fine - I really don't mind people using GPL if they believe that they want to keep things open, obviously. I also don't want people to distribute things as their own, but I feel that the MIT license conveys that - they're still required to retain attribution, but they aren't forced to bring their entire product under the terms of another license.

In this case, I love that you'd done a load of work on this to get it to this point and that it's available. I can't use it, but I can still contribute and help to make it better. And I love that you've been so responsive with it too - *that* is more important to open source :-)

**Comment by fakerybakery** [comment]
Just found this repo - super cool @mathoudebine! Have you considered using the zlib license, which doesn't place restrictions on linking but prohibits people from passing it off as their own? Thanks!
