### ISSUE TITLE
Erro de conexao

### ISSUE THREAD

**Issue by Digaruti01** [mathoudebine/turing-smart-screen-python#362]
I recently bought the 3.5 screen, but it is fixed to a white screen and I don't know what to do to make it work as I expected. I tried several times to install and uninstall the app, but it remains on the white screen, I'm about to return it to the seller.
![asdas](https://github.com/mathoudebine/turing-smart-screen-python/assets/148416925/003f3b23-cb67-44a3-ac8b-e98c41f9f802)

**Comment by FabioZumbi12** [comment]
Try to use another usb cable. I got a similar issue when using an incompatible usb cable (dont know why). Check the revision on config too.

**Comment by mathoudebine** [comment]
Can you show us what you have under "Serial ports" in your Device Manager? 
![rtaImage](https://github.com/mathoudebine/turing-smart-screen-python/assets/38615348/41af8d82-e210-4c02-a598-1cfe1f694d81)

**Comment by mathoudebine** [comment]
Closing this issue since inactive, please tag me if you want to reopen it.
