### ISSUE TITLE
ZeroDivisionError in sensors_librehardwaremonitor.py when page file is disabled on Windows 10

### ISSUE THREAD

**Issue by Sanichka** [mathoudebine/turing-smart-screen-python#390]
**Describe the bug**  
When page file is disabled in Windows 10 Memory_Stats thread get's exception due to division by zero

**To Reproduce**  
1. Go to Windows 10 Settings -> System -> About -> Advanced system settings -> Advanced tab -> Perfomance -> Advanced -> Virtual Memory Change -> Set no paging file
![image](https://github.com/mathoudebine/turing-smart-screen-python/assets/9090737/dfb7b122-c562-4973-8826-4f161933d159)
2. Configure USB screen(in my case USBpcmonitor 5) choose theme 5inchTheme2
3. Run in console: python main.py
4.  Get exception in console
![image](https://github.com/mathoudebine/turing-smart-screen-python/assets/9090737/60677f46-08f2-4f61-a396-0b941e40704e)

**Expected behavior**  
I've expected that there will be no errors in console.

**Screenshots / photos of the Turing screen**  
Screen is working and showing and refreshing info, but i'm not sure where is swap data is used.
![image](https://github.com/mathoudebine/turing-smart-screen-python/assets/9090737/64d11043-5833-4b01-818d-4a22a39cb9b5)

**Environment:**  
 - Smart screen model UsbPCMonitor 5
 - Revision of this project release 3.3.4
 - OS with version Windows 10
 - Python version Python 3.9.13
 - Hardware  AMD Ryzen 9 5900X, Nvidia 1070Ti

**Comment by mathoudebine** [comment]
Thanks for reporting this issue. I will fix it in the next version.

The crash happens in the memory thread, this is why you have no memory information displayed on screen:
![image](https://github.com/mathoudebine/turing-smart-screen-python/assets/38615348/3aff74a9-18c6-4b7f-a40d-dd5a4bdc2872)
But the other sensors (CPU, disk) and the program will continue to work
