### ISSUE TITLE
test_librehardwaremonitor.py does not show detailed Motherboard info - the standalone .exe does provide this

### ISSUE THREAD

**Issue by exelanz** [mathoudebine/turing-smart-screen-python#392]
### UPDATE: I guess this might be a matter of extending the output to include SubHardware and therefore not a Bug? ###

**Describe the bug**  
When I run LibreHardwareMonitor.exe I get detailed info on my Motherboard. When using the test_librehardwaremonitor.py I don´t get this information.

**To Reproduce**  
1. Run LibreHardwareMonitor.exe
2. Run test_librehardwaremonitor.py
3. Compare output

**Expected behavior**  
Same information from both apps

**Screenshots / photos of the Turing screen**  
Output of LibreHardwareMonitor.exe:
![image](https://github.com/mathoudebine/turing-smart-screen-python/assets/831364/0d0fc080-f503-4f42-90c7-00c5dba156b2)

Output of test_librehardwaremonitor.py (Just name of the motherboard, then it continues with storage components):
![image](https://github.com/mathoudebine/turing-smart-screen-python/assets/831364/cb9775b8-65e7-4048-b93a-1420bd6698ca)

**Environment:**  
 - Smart screen model: XuanFang 3.5”
 - Revision of this project: latest release
 - OS with version: Windows 11
 - Python version: tested with 3.11 and 3.12
 - Hardware:  ASUS TUF GAMING B550 plus WiFi II, AMD Ryzen 5600x and AMD Radeon rx 6700 xt
 
**Additional context**  
None - but can provide additional info if needed

**Comment by mathoudebine** [comment]
Hello! Thanks for reporting this issue, I can confirm it because I have the same motherboard as you, which will be easier to debug!

**Comment by mathoudebine** [comment]
I can confirm the behavior was linked to the SubHardware not being displayed. This branch https://github.com/mathoudebine/turing-smart-screen-python/tree/fix/392-test_librehardwaremonitorpy-does-not-show-detailed-motherboard-info-the-standalone-exe-does-provide-this now contains a fix to list these SubHardware in `test_librehardwaremonitor.py`, can you check if it fixes the issue for you?

**Comment by exelanz** [comment]
Yes the fix in the specified branch works for me. Output is as expected. Thanks!
