### ISSUE TITLE
Text position anchors

### ISSUE THREAD

**Issue by CaraesNaur** [mathoudebine/turing-smart-screen-python#398]
**Is your feature request related to a problem? If so, please describe the problem.**  
All displayed text is positioned with the top left corner of its bounding box at the specified pixel coordinates.

**Describe the feature / solution to your problem you'd like**  
The ability to specify various points on the text bounding box to place at the given coordinate.

X-axis reference points:

- Left
- Center
- Right

Y-axis reference points:

- Top
- Middle (vertical midpoint of box)
- Baseline (text baseline)
- Bottom

Essentially a subset of the CSS `position` property.  Thus, any theme entry which includes `X` and `Y` would also declare `POSITION`, i.e.:

    POSITION: CENTER MIDDLE # Defaults to TOP LEFT (current behavior)

This would allow for much more precise text placement.  Redraws after changing position would leave behind even more artifacts than current behavior, however this should only affect theme development.

**Describe alternatives you've considered / and or tested**  
None.

**Screenshots / photos & mockups of the Turing screen**  
N/A

**Environment:**  
 - Revision of this project: Release 3.3.4
 - OS with version: Kubuntu 22.04
 - Python version: 3.10.12
 - Hardware: Simulator (AMD FX-8350)

**Additional context**  

A diagram of the proposed positions:

![turing_position_map](https://github.com/mathoudebine/turing-smart-screen-python/assets/544558/64ee1c61-1e0e-40c8-9488-5a947a749f6e)

**Comment by mathoudebine** [comment]
Thanks for your feedback, it is now implemented with the merge of #487
