### ISSUE TITLE
COM port auto-discovery sometimes fails on Windows

### ISSUE THREAD

**Issue by bloor** [mathoudebine/turing-smart-screen-python#45]
**Describe the bug**  
Error when trying to execute the script from CMD:
`serial.serialutil.PortNotOpenError: Attempting to use a port that is not open`

**To Reproduce**  
Download the repository
Installed all the py modules required

**Screenshots / photos of the Turing screen**  
![image](https://user-images.githubusercontent.com/1420653/190413276-3387e90e-48dc-44c9-8d77-f6857c74a8aa.png)

**Environment:**  
 - Windows 10 (latest update to date)
 - Python version 3.9.1
 - Intel CPU 10875H, Nvidia 2070 RTX 

**Additional context**  
I am plugging the USB directly in the laptop, not in the usb-HUB
This is my first encounter with python and also with a 3.5" minidisplay. Is it supposed to not even turn on when cable is plugged in ? Did i get a faulty unit ? the LCD is dead.

**Comment by mathoudebine** [comment]
Hi,
I can confirm that on some Windows computers, the COM port auto-discovery does not work.
I can reproduce it on at least one computer, also a laptop with Windows 10.
Until I investigate this issue, you can edit `config.yaml` and indicate your COM port manually instead of `AUTO`

**Comment by mathoudebine** [comment]
And it is normal for the LCD to stay off when plugged if you have a B or flasghip revision.
The LCD should turn on after you run the program (without errors).

**Comment by bloor** [comment]
Yes. it's variant B. Ok.. i was just a bit worried it might be dead or something. 
I already tried with that software, but it does not run even after adding some "missing dlls". + its full chinese the files might be corrupted due to charset or something.
I`ll check some workarounds.

**Comment by bloor** [comment]
Manually putting COM3 worked, but I also didn't noticed my REVISION was A in config, instead of B.
WORKS AS INTENDED 👍 freaking love it. 10x for the help

**Comment by bloor** [comment]
donzo
