### ISSUE TITLE
"used" ram meaningless on linux + give wrong 'total'.

### ISSUE THREAD

**Issue by orzel** [mathoudebine/turing-smart-screen-python#450]
On linux/python, the Memory:used is fetched from psutil, but it's nothing really interesting. It corresponds to nothing in `top` for example.

That's, by itself, is a problem. But the code in `library/stats.py`  uses it to compute `total`. This is wrong, as explained on the [psutil documentation itself](https://psutil.readthedocs.io/en/latest/#memory).

For ex on one system, i got 128G of RAM, reported as 125 by `psutil.virtual_memory().total`, which is fine. But free is 42.7 and used 6.4, and as such turing-smart-screen-python displays "49.2". As a side note, i have no idea what those 6.4 are...

**Comment by mathoudebine** [comment]
Thanks for raising this issue, I was not aware of this
Basically we can use `(total - available)` for used memory
I'll create a PR for this
