### ISSUE TITLE
Intel i7-12700 no data showing up

### ISSUE THREAD

**Issue by varg404** [mathoudebine/turing-smart-screen-python#498]
**Describe the bug**  
CPU Data Only Shows Usage

**To Reproduce**  
On Startup

**Expected behavior**  
Show CPU Data

**Screenshots / photos of the Turing screen**  
![photo_2024-04-10_15-41-30](https://github.com/mathoudebine/turing-smart-screen-python/assets/13522231/20fc78f2-26a6-4b80-994e-644b2742c1d8)

**Environment:**  
 - Smart screen model: XuanFang 3.5
 - Revision of this project 
 - OS with version Windows 11 23H2
 - Python version 3.10.11
 - Hardware 12th Gen Intel Core i7-12700

**Additional context**  
Main Log + test_librehardwaremonitor.py Log below

Program is runnig as Admin!

`
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
10.04.2024 15:22:44 [WARNING] Found 2 GPUs on your system (0 AMD / 1 Nvidia / 1 Intel). Auto identify which GPU to use.
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Besitzer\Documents\miniscreen\library\scheduler.py", line 73, in wrap
    periodic(scheduler, interval, func)
  File "C:\Users\Besitzer\Documents\miniscreen\library\scheduler.py", line 64, in periodic
    action(*actionargs)
  File "C:\Users\Besitzer\Documents\miniscreen\library\scheduler.py", line 110, in CPUTemperature
    stats.CPU.temperature()
  File "C:\Users\Besitzer\Documents\miniscreen\library\stats.py", line 280, in temperature
    temperature = sensors.Cpu.temperature()
  File "C:\Users\Besitzer\Documents\miniscreen\library\sensors\sensors_librehardwaremonitor.py", line 214, in temperature
    return float(sensor.Value)
TypeError: float() argument must be a string or a real number, not 'NoneType'
10.04.2024 15:22:44 [DEBUG] This GPU will be used for stats: NVIDIA GeForce RTX 3070

Found LibreHardwareMonitorLib 0.9.3.0
Found HidSharp 2.1.0.0
Motherboard | Gigabyte B660M DS3H AX DDR4 | /motherboard
----------------------------------------------------
Cpu | 12th Gen Intel Core i7-12700 | /intelcpu/0
    Load | CPU Core #1 Thread #1 | 13.587522506713867
    Load | CPU Core #1 Thread #2 | 0.38230419158935547
    Load | CPU Core #2 Thread #1 | 4.559493064880371
    Load | CPU Core #2 Thread #2 | 0.0
    Load | CPU Core #3 Thread #1 | 0.0
    Load | CPU Core #3 Thread #2 | 0.0
    Load | CPU Core #4 Thread #1 | 0.0
    Load | CPU Core #4 Thread #2 | 0.4942655563354492
    Load | CPU Core #5 Thread #1 | 1.11808180809021
    Load | CPU Core #5 Thread #2 | 24.07919692993164
    Load | CPU Core #6 Thread #1 | 36.152503967285156
    Load | CPU Core #6 Thread #2 | 1.8293440341949463
    Load | CPU Core #7 Thread #1 | 0.49278736114501953
    Load | CPU Core #7 Thread #2 | 21.897720336914062
    Load | CPU Core #8 Thread #1 | 7.418745994567871
    Load | CPU Core #8 Thread #2 | 0.34897327423095703
    Load | CPU Core #9 | 17.17165756225586
    Load | CPU Core #10 | 16.50577163696289
    Load | CPU Core #11 | 17.42238998413086
    Load | CPU Core #12 | 16.865562438964844
    Load | CPU Total | 8.737259864807129
    Load | CPU Core Max | 36.152503967285156
    Temperature | CPU Core #1 | None
    Temperature | CPU Core #2 | None
    Temperature | CPU Core #3 | None
    Temperature | CPU Core #4 | None
    Temperature | CPU Core #5 | None
    Temperature | CPU Core #6 | None
    Temperature | CPU Core #7 | None
    Temperature | CPU Core #8 | None
    Temperature | CPU Core #9 | None
    Temperature | CPU Core #10 | None
    Temperature | CPU Core #11 | None
    Temperature | CPU Core #12 | None
    Temperature | CPU Package | None
    Temperature | CPU Core #1 Distance to TjMax | None
    Temperature | CPU Core #2 Distance to TjMax | None
    Temperature | CPU Core #3 Distance to TjMax | None
    Temperature | CPU Core #4 Distance to TjMax | None
    Temperature | CPU Core #5 Distance to TjMax | None
    Temperature | CPU Core #6 Distance to TjMax | None
    Temperature | CPU Core #7 Distance to TjMax | None
    Temperature | CPU Core #8 Distance to TjMax | None
    Temperature | CPU Core #9 Distance to TjMax | None
    Temperature | CPU Core #10 Distance to TjMax | None
    Temperature | CPU Core #11 Distance to TjMax | None
    Temperature | CPU Core #12 Distance to TjMax | None
    Temperature | Core Max | None
    Temperature | Core Average | None
    Clock | CPU Core #1 | None
    Clock | CPU Core #2 | None
    Clock | CPU Core #3 | None
    Clock | CPU Core #4 | None
    Clock | CPU Core #5 | None
    Clock | CPU Core #6 | None
    Clock | CPU Core #7 | None
    Clock | CPU Core #8 | None
    Clock | CPU Core #9 | None
    Clock | CPU Core #10 | None
    Clock | CPU Core #11 | None
    Clock | CPU Core #12 | None
----------------------------------------------------
Memory | Generic Memory | /ram
    Data | Memory Used | 13.693897247314453
    Data | Memory Available | 18.06795883178711
    Load | Memory | 43.11428451538086
    Data | Virtual Memory Used | 17.603450775146484
    Data | Virtual Memory Available | 21.301185607910156
    Load | Virtual Memory | 45.2476921081543
----------------------------------------------------
GpuNvidia | NVIDIA GeForce RTX 3070 | /gpu-nvidia/0
    Temperature | GPU Core | 55.0
    Clock | GPU Core | 225.0
    Clock | GPU Memory | 810.0
    Fan | GPU Fan 1 | 0.0
    Fan | GPU Fan 2 | 0.0
    Control | GPU Fan 1 | 32.0
    Control | GPU Fan 2 | 32.0
    Load | GPU Core | 29.0
    Load | GPU Memory Controller | 30.0
    Load | GPU Video Engine | 24.0
    Load | GPU Bus | 0.0
    Load | GPU Power | 12.10099983215332
    Load | GPU Board Power | 13.567000389099121
    SmallData | D3D Dedicated Memory Used | 1480.3671875
    SmallData | D3D Shared Memory Used | 106.0234375
    Load | D3D 3D | 0.0
    Load | D3D Overlay | 0.0
    Load | D3D Video Decode | 0.0
    Load | D3D Copy | 0.0
    Load | D3D Copy | 0.0
    Load | D3D Security | 0.0
    Load | D3D Video Encode | 21.615402221679688
    Load | D3D Video Processing | 0.0
    Load | D3D VR | 0.0
    Temperature | GPU Hot Spot | 66.71875
    SmallData | GPU Memory Total | 8192.0
    SmallData | GPU Memory Free | 6546.0
    SmallData | GPU Memory Used | 1645.0
    Load | GPU Memory | 20.090579986572266
    Power | GPU Package | 27.229000091552734
    Throughput | GPU PCIe Rx | 3072.0
    Throughput | GPU PCIe Tx | 0.0
----------------------------------------------------
GpuIntel | Intel(R) UHD Graphics 770 | /gpu-intel-integrated/\\?\PCI#VEN_8086&DEV_4680&SUBSYS_D0001458&REV_0C#3&11583659&0&10#{1ca05180-a699-450a-9a0c-de4fbe3ddd89}
    SmallData | D3D Shared Memory Used | 0.46484375
    Load | D3D 3D | 0.0
    Load | D3D Video Decode | 0.0
    Load | D3D Copy | 0.0
    Load | D3D Video Processing | 0.0
    Load | D3D Video Decode | 0.0
    Load | D3D Other | 0.0
    Load | D3D Other | 0.0
    Load | D3D Other | 0.0
    Load | D3D Other | 0.0
    Load | D3D Other | 0.0
    Load | D3D GDI Render | 0.0
    Load | D3D Video Processing | 0.0
    Load | D3D Other | 0.0
----------------------------------------------------
Storage | E15-1TB-PHISON-SSD-B47R | /nvme/0
    Temperature | Temperature | 50.0
    Level | Available Spare | 100.0
    Level | Available Spare Threshold | 5.0
    Level | Percentage Used | 9.0
    Data | Data Read | 14967.0
    Data | Data Written | 20188.0
    Load | Used Space | 25.556365966796875
    Load | Read Activity | 4.8964746383717284e-05
    Load | Write Activity | 1.724359390209429e-05
    Load | Total Activity | 99.99778747558594
    Throughput | Read Rate | None
    Throughput | Write Rate | None
----------------------------------------------------
Storage | Samsung SSD 980 1TB | /nvme/1
    Temperature | Temperature | 42.0
    Level | Available Spare | 100.0
    Level | Available Spare Threshold | 10.0
    Level | Percentage Used | 0.0
    Data | Data Read | 11336.0
    Data | Data Written | 6422.0
    Temperature | Temperature 1 | 42.0
    Temperature | Temperature 2 | 51.0
    Load | Used Space | 39.045692443847656
    Load | Read Activity | 7.321616976696532e-06
    Load | Write Activity | 9.337640562989691e-07
    Load | Total Activity | 99.99775695800781
    Throughput | Read Rate | None
    Throughput | Write Rate | None
----------------------------------------------------
Network | Bluetooth-Netzwerkverbindung | /nic/{AAE168F0-4F87-41F2-8037-60C4F86A23DE}
    Data | Data Uploaded | 0.0
    Data | Data Downloaded | 0.0
    Throughput | Upload Speed | 0.0
    Throughput | Download Speed | 0.0
    Load | Network Utilization | 0.0
----------------------------------------------------
Network | Ethernet | /nic/{F553F564-ADDF-4E9D-BB47-C329375F5967}
    Data | Data Uploaded | 4.851507663726807
    Data | Data Downloaded | 66.0684585571289
    Throughput | Upload Speed | 362.0459899902344
    Throughput | Download Speed | 415.1460876464844
    Load | Network Utilization | 0.0006217536283656955
----------------------------------------------------
Network | LAN-Verbindung* 10 | /nic/{6D31047E-0B7A-4722-A4B5-084CFE53DE3D}
    Data | Data Uploaded | 0.0
    Data | Data Downloaded | 0.0
    Throughput | Upload Speed | 0.0
    Throughput | Download Speed | 0.0
    Load | Network Utilization | 0.0
----------------------------------------------------
Network | LAN-Verbindung* 9 | /nic/{160BF641-26F0-4C95-AC0D-0A9B8A3B2C7F}
    Data | Data Uploaded | 0.0
    Data | Data Downloaded | 0.0
    Throughput | Upload Speed | 0.0
    Throughput | Download Speed | 0.0
    Load | Network Utilization | 0.0
----------------------------------------------------
Network | vEthernet (BluestacksNxt) | /nic/{DD652D93-D4FD-4324-850E-15D725CDDEAB}
    Data | Data Uploaded | 28.21662139892578
    Data | Data Downloaded | 0.461410790681839
    Throughput | Upload Speed | 0.0
    Throughput | Download Speed | 0.0
    Load | Network Utilization | 0.0
----------------------------------------------------
Network | vEthernet (Default Switch) | /nic/{7FB9E47A-E931-4222-8BDA-CE7393135775}
    Data | Data Uploaded | 0.014429082162678242
    Data | Data Downloaded | 0.0
    Throughput | Upload Speed | 0.0
    Throughput | Download Speed | 0.0
    Load | Network Utilization | 0.0
----------------------------------------------------
Network | WLAN | /nic/{CCF45E6E-6594-45A4-A8E2-B66946BFC166}
    Data | Data Uploaded | 0.0
    Data | Data Downloaded | 0.0
    Throughput | Upload Speed | 0.0
    Throughput | Download Speed | 0.0
    Load | Network Utilization | 0.0
----------------------------------------------------

`

**Comment by mathoudebine** [comment]
Hi, it seems temperature and clock data from your CPU are not read properly by LibreHardwareMonitor
Can you download the LHM full program from here: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/download/v0.9.3/LibreHardwareMonitor-net472.zip and run it?
Can you see temperature data from your CPU like in this screenshot?
![Capture d’écran 2024-04-26 134945](https://github.com/mathoudebine/turing-smart-screen-python/assets/38615348/65bbf138-308d-4605-8fe9-bc5e94658aa3)

**Comment by GuyFromTurkey** [comment]
@mathoudebine i don't have CPU temperature when i open LibreHardwareMonitor.exe

![image](https://github.com/user-attachments/assets/0f2b372e-89f1-450d-8cd5-c98409816f70)

**Comment by GuyFromTurkey** [comment]
> @mathoudebine i don't have CPU temperature when i open LibreHardwareMonitor.exe
> 
> ![image](https://private-user-images.githubusercontent.com/178640482/358833990-0f2b372e-89f1-450d-8cd5-c98409816f70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4ODcxMzUsIm5iZiI6MTcyMzg4NjgzNSwicGF0aCI6Ii8xNzg2NDA0ODIvMzU4ODMzOTkwLTBmMmIzNzJlLTg5ZjEtNDUwZC04Y2Q1LWM5ODQwOTgxNmY3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwOTI3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzMzN2U0ZjQ2Y2FhN2M3Y2VlMzFiMmU4YWYwOTlhOTExNjE5MjM3YTdmYTFiMjA4MjgxZTE5YmZlZDA2MWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DKC2TiWmCjhoVl3_-EzaPSPfJ53jdvpreZamH8ZkrkU)

My antivirus was triggered when I ran test_librehardwaremonitor.py "LibreHardwareMonitor.sys" was potentially dangerous, I added an exception and I had my values ​​from my CPU.
I add exception too with "python.sys" who is at this path "C:\Users\xxx\AppData\Local\Programs\Python\Python312"

Everything works now, I hope I was able to help you.
