### ISSUE TITLE
Not correct CPU temperature

### ISSUE THREAD

**Issue by pndkhanh** [mathoudebine/turing-smart-screen-python#5]
It appears to me that the app is showing the temperature of core #6 instead of the CPU package.
For i.e. please refer to the below screenshot.
Expected: 68*
Actual: 48* (This is what showing in the screen for the CPU temperature)
![image](https://user-images.githubusercontent.com/20035076/147600517-3cac6ad7-c937-487b-8fce-aec100bfc831.png)

**Comment by mathoudebine** [comment]
Hi, this is not the repository for the official Windows app for the Turing smart screen, but an alternative Python multi-platform script to do some simple operations on the screen.
For support on the official app, please contact the seller of your screen
