### ISSUE TITLE
On mac, python-tk is already installed via homebrew, but the error to install tkinter persists.

### ISSUE THREAD

**Issue by Numbski** [mathoudebine/turing-smart-screen-python#516]
**Describe the bug**  
I can try to install python-tk on Mac, but it is already installed:

```Garou:~/git/turing-smart-screen-python  tshadwick$ brew install python-tk
==> Downloading https://formulae.brew.sh/api/formula.jws.json
##O=#    #
==> Downloading https://formulae.brew.sh/api/cask.jws.json

Warning: python-tk@3.12 3.12.3 is already installed and up-to-date.
To reinstall 3.12.3, run:
  brew reinstall python-tk@3.12
```

So then I go to launch configure.py (while in the same directory):

```Garou:~/git/turing-smart-screen-python  tshadwick$ python3 configure.py
[ERROR] Tkinter dependency not installed. Please follow troubleshooting page: https://github.com/mathoudebine/turing-smart-screen-python/wiki/Troubleshooting#all-os-tkinter-dependency-not-installed
Garou:~/git/turing-smart-screen-python  tshadwick$
```

Verifying that I am indeed using python3 from homebrew:

```Garou:~/git/turing-smart-screen-python  tshadwick$ which python3
/usr/local/bin/python3
Garou:~/git/turing-smart-screen-python  tshadwick$ ls -alhs /usr/local/bin/python3
0 lrwxr-xr-x  1 tshadwick  admin    40B Apr 19 12:03 /usr/local/bin/python3 -> ../Cellar/python@3.12/3.12.3/bin/python3
```

**To Reproduce**  
1. ```homebrew update && homebrew upgrade && homebrew install python-tk```
2. ```python3 configure.py```

**Expected behavior**  
Literally anything but this error.

**Screenshots / photos of the Turing screen**  
Add screenshots or photos of the rendering on the smart screen to help explain your problem.
You can drag and drop photos here to add them to the description.

**Environment:**  
 - Smart screen model [e.g. Turing 5", XuanFang 3.5”]
 - Revision of this project [e.g. 3.0.0, `main` branch, specific commit]
 - OS with version [e.g. Windows 11, Ubuntu 22.04]
 - Python version [e.g. Python 3.10]
 - Hardware [e.g. Intel CPU, Nvidia GPU, Raspberry Pi 3 B+ ...]

**Additional context**

**Comment by Numbski** [comment]
This is so weird.  I switched to a venv and this resolved itself.  So very confusing.

**Comment by 0xnth** [comment]
> This is so weird.  I switched to a venv and this resolved itself.  So very confusing.
Yoo I have the same problem as you but no way to succeed on macos sonoma, my panel is smart screen turning TURZX 3.5", i will try installing python with venv
