### ISSUE TITLE
Device not recognised (short response to HELLO) on Windows 11

### ISSUE THREAD

**Issue by MeishiSmile** [mathoudebine/turing-smart-screen-python#54]
**Describe the bug**
The screen is not working due to the device not being recognized (short response to HELLO).

**To Reproduce**

1. Run main.py

**Expected behavior**
The product to working normally.

**Environment:**

- Windows 11 Laptop (Intel i5-10300H / GTX 1650)
-  Python 3.10.7
- XuanFang smart screen (Version B)

**Additional context:**

- The original vendor app "ExtendScreen.exe" working fine.
- If I set COM to AUTO: "Cannot find COM port automatically, please set it manually in config.yaml"

![Screenshot_1](https://user-images.githubusercontent.com/114492912/192534105-16f3c24a-9a63-4b6e-ae07-7af4f8a098d6.png)

**Comment by mathoudebine** [comment]
Hi, can you try using revision A in config.yaml to see if it works? Maybe some XuanFang smart screen use revision A protocol.
Do you have a 3.5" LCD or a 5"?

**Comment by MeishiSmile** [comment]
Hello. When using the A revision:
![image](https://user-images.githubusercontent.com/114492912/192620148-d2dcdbe7-07ae-4e39-ad71-b21657f4ac1d.png)
It's a 3.5" screen. 
Thanks

**Comment by mathoudebine** [comment]
The latest error is unexpected, the serial port should be open without errors.
Maybe your screen got stuck in a bad state.
Can you unplug the screen, plug it back, then run again with revision A? Thanks

**Comment by mathoudebine** [comment]
Also, can you check that the back of your screen looks like one of the 3 models displayed here?  
  
![](https://raw.githubusercontent.com/mathoudebine/turing-smart-screen-python/main/res/docs/AllVersions.jpg)

**Comment by MeishiSmile** [comment]
It's the same as Version B.

**Comment by mathoudebine** [comment]
Be sure to test also with the app from the vendor (XFZ) to check if your display works correctly.
On my side, i will check the HELLO command to see if it is implemented correctly

**Comment by MeishiSmile** [comment]
Yes, the vendor app works as intended.
Thanks for your effort!

**Comment by DanchoParker** [comment]
> Be sure to test also with the app from the vendor (XFZ) to check if your display works correctly. On my side, i will check the HELLO command to see if it is implemented correctly

Hi. 

https://lgb123-1253504678.cos.ap-beijing.myqcloud.com/35inchENG.rar

this app from this site https://www.turzx.com/2021/11/09/download/ and another sources have na backdoor Gen:NN.ZemsilF.34726.pn0@aKVJPNc and W32.AIDetectNet.01 on virustotal.com

this is false positive or what?

**Comment by mathoudebine** [comment]
Hello,
New analysis is here: https://www.virustotal.com/gui/file/820b4214fe9e73b09bcaf351f5c2343b54b2d78dfd08356e202d5c15c6941f59

I think they are false positive:
BitDefenderTheta finds a Gen:XXXX so it did not identify a specific threat, but a generic behavior that could be considered as malicious
Same for Malwarebytes with Malware.Heuristic.1003
These are heuristic filters to detect threats based on behaviors.
This may be because the app monitors the hardware and the network, which is also done by some malware.

If you still have a doubt, you can use this project rather than the original program, but there are some limitations in Windows: see here: https://github.com/mathoudebine/turing-smart-screen-python/wiki/System-monitor-%3A-hardware-support

**Comment by mathoudebine** [comment]
Hello @MeishiSmile did you manage to fix your issue?
Can you also check if the original app ExtendScreen is not running in background before running `main.py`

**Comment by MeishiSmile** [comment]
Hello @mathoudebine, unfortunately, it doesn't work on my machine. I also double-checked if the ExtendScreen was running in the background, but that was not the case.

**Comment by Richard444** [comment]
Com port can be variable by device, with windows machines you can find the proper tag in device manager
![image](https://user-images.githubusercontent.com/31082767/212459732-8eb75f19-af2d-42d2-ae0d-e97b4040e724.png)

**Comment by mathoudebine** [comment]
Closing this bug as inactive since January, tag me or open another bug report if you still have issues
