### ISSUE TITLE
Issue with Task Scheduler

### ISSUE THREAD

**Issue by ispascelgras** [mathoudebine/turing-smart-screen-python#625]
Hey, sorry for asking.

I have an issue with the Task Scheduler and I was wondering if you have any ideas of how to fix it.
I follow all the steps, but when I check "Run with highest privileges" and press OK I receive the following error.

![image](https://github.com/user-attachments/assets/97975275-728e-444d-8ee6-7c1636e4d9c9)

Everything is running on Administrator rights, I've already performed the sfc /scannow.

Thanks!

**Comment by c0ldJS** [comment]
This is an operating system matter, not a bug with `turing-smart-screen-python`, and should probably move to Discussions.

Fully scheduling the task requires configurations on the `General`, `Triggers`, and `Actions` tabs and missing any of them can produce that error. Additionally, if (for some strange reason) Task Manager isn't participating in the `SYSTEM` group then the security options go sideways and that error can also be returned.

In the provided screenshot, is the `Details` column showing the full path you configured for an action or is that being cut off?

**Comment by ispascelgras** [comment]
Hey, 

Thanks for answering! 
Task Manager runs as SYSTEM, which is in the same group as my user "iSPAS"
I'm publishing some screenshots for context:




![image](https://github.com/user-attachments/assets/f4b8dfb4-fe4e-44a3-9f92-56f18bcf6f85)
![image](https://github.com/user-attachments/assets/c4a2d76f-36db-4ed5-aec4-5b5d69b95ab8)
![image](https://github.com/user-attachments/assets/e82bd124-fb48-426b-8a73-295b03a3e786)
![image](https://github.com/user-attachments/assets/e83f6fe4-75e1-4e37-8320-22ecf0fe03df)





_In the provided screenshot, is the Details column showing the full path you configured for an action or is that being cut off?_

Yes, it's the full path to `pythonw.exe`, as shown in the 3rd screenshot. The Start in goes to the Root folder of `\turing-smart-screen-python-3.6.0\turing-smart-screen-python-3.6.0`

I have to tell you that I run on Windows 11.

Is there anything else you need, or does it ring a bell from what I already posted?

Thanks and Merry Christmas :)!

**Comment by AoXNeR** [comment]
same exact issue here.

**Comment by c0ldJS** [comment]
In that last screenshot, when `Start in:` is being configured, is that a full path including the relevant drive? Or is it precisely `\turing-smart-screen-python-3.6.0\turing-smart-screen-python-3.6.0`?

**Comment by AoXNeR** [comment]
Fixed when changing task user to "Administrators "

**Comment by ispascelgras** [comment]
Thank you all for your help!, @AoXNeR was right, that fixed the issue.

**Comment by mathoudebine** [comment]
Thanks, I updated the wiki page with the fix!
