### ISSUE TITLE
Fourth hardware revision identifies as A

### ISSUE THREAD

**Issue by RussNelson** [mathoudebine/turing-smart-screen-python#63]
The TSS I just received identifies as A from the software end, but has a fully enclosed front and back. No electronics visible other than the two USB-C connectors.

https://photos.app.goo.gl/ki2Gb5mvS6evMk186

**Comment by RussNelson** [comment]
![PXL_20221026_002931881](https://user-images.githubusercontent.com/1156994/197909060-67c9651c-7230-4447-a621-eb19935e6ff2.jpg)

**Comment by RussNelson** [comment]
I've added it to the AllVersions.jpg picture in res/docs/

![AllVersions](https://user-images.githubusercontent.com/1156994/197909381-5a9f7829-3fb2-4e54-af45-ffe4ef49c7ba.jpg)

**Comment by RussNelson** [comment]
Submitted a PR instead.

**Comment by mathoudebine** [comment]
Interesting! They finally made a proper case for the A revision
It means they also continue to sell it for which i'm surprised. Can you tell me where you bought it?
Don't hesitate to open bugs if you see something wrong when using this project with your screen!

**Comment by RussNelson** [comment]
https://www.geekbuying.com/item/3-5-Inch-IPS-TYPE-C-Secondary-Screen-CPU-GPU-RAM-HDD-Monitoring-501430.html
Paid $20 (discounted) for two of them, but the price is now $23.
