### ISSUE TITLE
add US locations or let detect location

### ISSUE THREAD

**Issue by lessmarble** [mathoudebine/turing-smart-screen-python#83]
please add US locations or allow software to automatically detect location

I specifically want US /denver

**Comment by mathoudebine** [comment]
Hello, are you talking about the UsbMonitor.exe / ExtendScreen.exe software?
If so, please read the disclaimer in the front page: https://github.com/mathoudebine/turing-smart-screen-python#readme

This project is an open-source alternative software, not the original software for the Turing smart screen.
For support on the original software, please contact the seller of your Turing screen or the official forum here: http://discuz.turzx.com/
