### ISSUE TITLE
Incorrect CPU clock

### ISSUE THREAD

**Issue by Rand0m80** [mathoudebine/turing-smart-screen-python#86]
**Describe the bug**  
Incorrect CPU clock is displayed

**To Reproduce**  
Normal run

**Expected behavior**  
After running project, CPU frequency displayed on my xuanfang display as 3.7 GHz and dont changing.
In the same time MSI hardware monitor correctly displayed frequency as changing value from 900 to 4795 MHz.

**Screenshots / photos of the Turing screen**  

![Shot](https://user-images.githubusercontent.com/118651084/202903221-2c8c1cb0-94cd-4ad4-a27d-be9ce228c78e.jpg)

**Environment:**  
 - Release or branch of this project [2.1.0]
 - OS with version [Windows 10 ver. 21H2]
 - Python version [Python 3.11.0]
 - Hardware [CPU Intel i5-9600K OC to 4.8 GHz, MB MSI Z370 SLI+]

**Additional context**  
Maybe problem somewhere here 
![20221120_160806](https://user-images.githubusercontent.com/118651084/202903850-0b8d5d17-d85e-45cc-a64f-df580c74726e.jpg)

**Comment by Rand0m80** [comment]
All works fine. Thank you.

**Comment by mathoudebine** [comment]
Fixed in 2.2.0 release
