### ISSUE TITLE
Screen is not showing CPU temperature :(

### ISSUE THREAD

**Issue by URSUS164** [mathoudebine/turing-smart-screen-python#9]
Hi, I have a issue with my screen because it's not showing CPU temperature and internet speed. I don't know what causes this kind of problem. Currently I'm running on Win 11. Is there any option in settings or BIOS/UEFI I should enable or disable?(maybe sth is blocking that kind of data). Thanks for help :)

**Comment by mathoudebine** [comment]
Hi, unfortunately this is not the repository for the official Windows app for the Turing smart screen ☹️ 
This is an alternative Python script to do some simple operations on the screen without using official app.
For support on the official app, please contact the seller of your screen, i don't use it so i cannot help you
